version: '2.0'
services:
  config-spring-boot:
    image: config-spring-boot
    ports:
        - "8888:8888"
    networks:
        - seted-network

  product-spring-boot:
    image: product-spring-boot
    
    depends_on:
        - config-spring-boot
    networks:
        - seted-network

  discovery-spring-boot:
    image: discovery-spring-boot
    ports:
        - "8761:8761"
    depends_on:
        - config-spring-boot
    networks:
        - seted-network

  proxy-spring-boot:
    image: product-spring-boot
    ports:
        - "9999:9999"
    depends_on:
        - config-spring-boot
    networks:
        - seted-network

networks:
  seted-network:
    driver: bridge